# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Cryptographic recipes and primitives for Python
brew "cryptography"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Automate deployment, configuration, and upgrading
brew "ansible"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# New way of working with Protocol Buffers
brew "buf"
# Utility for cleaning up unused build files generated by Cargo
brew "cargo-sweep"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Formatting tools for C, C++, Obj-C, Java, JavaScript, TypeScript
brew "clang-format"
# Cross-platform make
brew "cmake"
# Create and run Linux containers using lightweight virtual machines
brew "container", link: false
# Reimplementation of ctags(1)
brew "ctags"
# Diff that understands syntax
brew "difftastic"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Framework for layout and rendering of i18n text
brew "pango"
# Command-line fuzzy finder written in Go
brew "fzf"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Interpreted, interactive, object-oriented programming language
brew "python@3.13"
# Quickly rewrite git repository history
brew "git-filter-repo"
# Git extension for versioning large files
brew "git-lfs"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Command-driven, interactive function plotting
brew "gnuplot"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Like cURL, but for gRPC
brew "grpcurl"
# World's fastest and most advanced password recovery utility
brew "hashcat"
# C/C++ and Java libraries for Unicode and globalization
brew "icu4c@76"
# Git-compatible distributed version control system
brew "jj"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Handy way to save and run project-specific commands
brew "just"
# Curses-based tool for viewing and analyzing log files
brew "lnav"
# Fast, async, resource-friendly link checker
brew "lychee"
# Array framework for Apple silicon
brew "mlx"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
# Remote terminal application
brew "mosh"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Manage multiple Node.js versions
brew "nvm"
# Command-line Git information tool
brew "onefetch"
# On-chip debugging, in-system programming and boundary-scan testing
brew "open-ocd"
# OCR (Optical Character Recognition) engine
brew "tesseract"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Password generator
brew "pwgen"
# Core utilities for Python packages
brew "python-packaging"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Build tool for Scala projects
brew "sbt"
# Contract-oriented programming language
brew "solidity"
# SSH server & client auditing
brew "ssh-audit"
# Cross-shell prompt for astronauts
brew "starship"
# User interface to the TELNET protocol
brew "telnet"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# CLI tool that moves files or folder to the trash
brew "trash", link: true
# Command-line unarchiving tools supporting multiple formats
brew "unar"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Yet Another Dotfiles Manager
brew "yadm"
# JavaScript package manager
brew "yarn"
# Blazing fast terminal file manager written in Rust, based on async I/O
brew "yazi"
# Tool for managing your YubiKey configuration
brew "ykman"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Pluggable terminal workspace, with terminal multiplexer as the base feature
brew "zellij"
# Programming language designed for robustness, optimality, and clarity
brew "zig"
# Language Server for Zig
brew "zls"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Command-line interface for 1Password
cask "1password-cli"
# Terminal-based AI coding assistant
cask "claude-code"
npm "yarn"
